# https://taskfile.dev

version: '3'

vars:
  DEV_MODE: '{{.DEV_MODE | default "true"}}' # you need to explictly force non-dev to make things easier
  YML_FILES: "-f docker-compose.yml {{if eq .DEV_MODE `true`}}-f dev.docker-compose.yml{{end}}"

tasks:
  config:
    cmds:
    - docker compose {{.YML_FILES}} config

  build:
    cmds:
    - docker compose {{.YML_FILES}} build {{.CLI_ARGS}}

  up:
    cmds:
    - docker compose {{.YML_FILES}} up -d {{.CLI_ARGS}}

  down:
    cmds:
    - docker compose {{.YML_FILES}} down {{.CLI_ARGS}}

  poetry-lock:
    cmds:
    - docker compose {{.YML_FILES}} run --rm spiffworkflow-connector poetry lock

  poetry-install:
    cmds:
    - docker compose {{.YML_FILES}} run --rm spiffworkflow-connector poetry install

  # Reset the system for rapid development
  # *** NOTE: THIS WORKFLOW FOR DEV ONLY ***
  reset:
    cmds:
    - echo "*** Dev Mode is {{.DEV_MODE}} ***"
    - task: down
    - task: build
      vars: { CLI_ARGS: "--no-cache" }
    - task: poetry-install
      #we need to do this after our install to deal with permissions issues due to mounting this as a volume...
    - task: up

  test_prod:
    cmds:
    - echo "*** Dev Mode is {{.DEV_MODE}} ***"
    - task: down
    - task: build
      vars: { CLI_ARGS: "--no-cache" }
    - task: up
