# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
    - echo "{{.GREETING}}"
    silent: true

  # build the image locally
  # pass in BUILD_ARGS ex `task build BUILD_ARGS=--no-cache`
  build:
    deps: [ down ]
    cmds:
    - docker compose build --build-arg BUILD_ARGS=${BUILD_ARGS}

  up:
    cmds:
    - docker compose up -d

  down:
    cmds:
    - docker compose down

  reset:
    cmds:
    - docker compose down -v

  poetry-install:
    cmds:
    - docker compose run --rm spiffworkflow-connector poetry install --no-root

  powerwash:
    cmds:
    - task: down
    - task: build
      vars: { BUILD_ARGS: '--no-cache' }
      silent: true
    - task: poetry-install
    - task: up
