# https://taskfile.dev

version: '3'

vars:
  DEV_MODE: '{{.DEV_MODE | default "true"}}' # you need to explictly force non-dev to make things easier
  YML_FILES: "-f docker-compose.yml {{if eq .DEV_MODE `true`}}-f dev.docker-compose.yml{{end}}"

tasks:
  config:
    cmds:
    - docker compose {{.YML_FILES}} config

  build:
    cmds:
    - docker compose {{.YML_FILES}} build {{.CLI_ARGS}}

  up:
    cmds:
    - docker compose {{.YML_FILES}} up -d {{.CLI_ARGS}}

  down:
    cmds:
    - docker compose {{.YML_FILES}} down {{.CLI_ARGS}}

  poetry-lock:
    cmds:
    - docker compose {{.YML_FILES}} run --rm spiffworkflow-connector poetry lock

  poetry-install:
    cmds:
    - docker compose {{.YML_FILES}} run --rm spiffworkflow-connector poetry install

  # reset the system for rapid development
  reset:
    cmds:
    - echo "*** Dev Mode is {{.DEV_MODE}} ***"
    - task: down
      vars: { CLI_ARGS: "-v" }
    - task: build
      vars: { BUILD_ARGS: '--no-cache' }
    - task: poetry-install
    - task: up
