---
name: 2 - Publish & Deploy

on:
  push:
    branches:
      - main

jobs:
  ghcr_publish:
    name: Publish Images on GHCR
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Spiffworkflow-Connector
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/gsa-tts/spiffworkflow-connector:latest


